version: '3.8'

services:
  web:
    build: ./seismo_helper
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./seismo_helper/:/seismo_helper/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
