version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  web:
    build: ./seismo_helper
    command: gunicorn seismo_helper.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_value:/seismo_helper/static/
      - media_value:/seismo_helper/media/
#    ports:
#      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - 80:80

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - media_value:/var/html/
      - static_value:/var/html/

    depends_on:
      - web


volumes:
  postgres_data:
  static_value:
  media_value: