version: '3.8'

services:
  web:
    build: ./seismo_helper
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_value:/seismo_helper/static/
      - media_value:/seismo_helper/media/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
  static_value:
  media_value: