# Generated by Django 3.2.3 on 2023-07-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='p_peak',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trace',
            name='s_peak',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trace',
            name='timedelta',
            field=models.IntegerField(default=5),
        ),
    ]
