# Generated by Django 3.2.3 on 2023-07-05 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0002_station_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trace',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces',
                                    to='backend.event'),
        ),
        migrations.AlterField(
            model_name='trace',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trace',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traces',
                                    to='backend.station'),
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels',
                                            to='backend.trace')),
            ],
        ),
    ]
