# Generated by Django 3.2.3 on 2023-07-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20230708_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
