# Generated by Django 3.2.3 on 2023-07-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20230711_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='trace',
            name='timedelta',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
