# Generated by Django 3.2.3 on 2023-07-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_trace_timedelta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='z',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
